#
# Module manifest for module 'better-tree'
#
# Generated by: Alex Antoniou
#
# Generated on: 21/10/2021
#

@{
    RootModule        = 'better-tree.psm1'
    ModuleVersion     = '0.0.1'
    GUID              = 'c7fc5950-5aa8-455d-83c3-dc1e8b2b743f'
    Author            = 'Alex Antoniou'
    CompanyName       = ''
    Copyright         = '(c) Alex Antoniou. All rights reserved.'
    # Description = ''

    FileList          = @('better-tree.psd1', 'better-tree.psm1')
    FunctionsToExport = "Get-Tree"
    AliasesToExport   = "tree"

    PrivateData       = @{
        PSData = @{
            Tags       = @("tree", "file-system")
            LicenseUri = 'https://github.com/antoniouaa/better-tree/blob/master/LICENSE'
            ProjectUri = 'https://github.com/antoniouaa/better-tree/'
        }

    }
}

